name = "hotnow"
type = "javascript"
compatibility_date = "2024-11-01"

# Pages 构建配置
pages_build_output_dir = "dist/output/public"

# 环境变量
[env.production]
vars = { YOUTUBE_PROXY_URL = "https://hotnow-youtube-proxy.13632833907.workers.dev", NODE_VERSION = "22", CF_PAGES = "1" }
